In [8]:
import numpy as np

In [9]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [10]:
x + y

array([ 7, 13, 12])

2 dimentional array below

In [11]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [16]:
x.ndim
x.dtype

dtype('int64')

In [18]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [19]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [20]:
x.shape

(2, 2)

A method is a function associated with an object. e.g. x.sum()

In [23]:
x = np.array([3, 4, 5])
x.sum()

np.int64(12)

In [24]:
x= np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape(2, 3)
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [ ]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)


Modifying `x_reshape` also modified `x` because the two objects occupy the same space in memory.
 

    

Numpy arrays are sequence of rows called row-major ordering as opposed to column-major ordering

In [25]:
my_tuple = (1, 2, 3)
my_tuple[0] = 4

TypeError: 'tuple' object does not support item assignment

Concatenates note adds with a list.

In [27]:
np.sqrt(x)
x**2

array([ 1,  4,  9, 16, 25, 36])

In [7]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

In [6]:
x = [3, 4, 5]
x

[3, 4, 5]

In [5]:
"hello" + " " + "world"

'hello world'

In [4]:
3 + 5

8

In [ ]:
print?

In [ ]:
print('fit a model with', 11, 'variables')

fit a model with 11  variables
